name: Deploy to dev

on:
    push:
        tags:
            - 'v*'

jobs:
    build_and_deploy:
        environment:
            name: firebase
            url: "https://workshop-11-6-2.web.app"
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 18

            - name: Install dependencies
              run: npm ci  

            - name: Build React
              run: npm run build

            - name: Deploy to firebase
              run: npm install -g firebase-tools@latest
            - run: firebase deploy --only hosting:prod --token "$FIREBASE_TOKEN"
              env:
                FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}